# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

project: Thesis
title: Long-term Study of the Sun
copyright: '2023, Bibhuti'
author: Bibhuti Kumar Jha

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: thesis.tex


# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - allcitation.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: false

sphinx:
  config:
    html_theme: sphinx_rtd_theme
    bibtex_reference_style: author_year
    navigation_depth: 4
  extra_extensions:
    - sphinx_inline_tabs
  mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extensions:
- sphinxcontrib.bibtex

parse:
  myst_substitutions:
    Rsun: $~{\rm R}_\odot$
    AA: $~\mathring{{\rm A}}$

myst:
  enable_extensions: ["colon_fence"]


